### model
model_name_or_path: /mnt/models/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
loraplus_lr_ratio: null
use_rslora: false
use_dora: false
create_new_adapter: false

### dataset
dataset: gsm8k_train
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /root/output/qwen2.5-3b-gsm8k-lora
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: none

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
optim: adamw_torch
seed: 42

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
load_best_model_at_end: true
metric_for_best_model: loss
greater_is_better: false

### save
save_total_limit: 3
save_only_model: false
